spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE

remote:
  users:
    base-url: https://dwp-techtest.herokuapp.com
    users-in-london: ${remote.users.base-url}/city/London/users
    all-users: ${remote.users.base-url}/users

logging:
  file:
    max-history: 5
  level:
    ROOT: ERROR
    uk:
      gov: INFO

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true