version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

  deploy:
    steps:
      - checkout
      - run:
          name: Deploy main branch to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: SonarCloud

      - deploy:
          context: Heroku
          requires:
            - build
